# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(370, 20, 361, 491))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.ui_lne_temperature = QtWidgets.QLineEdit(self.groupBox)
        self.ui_lne_temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_lne_temperature.setObjectName("ui_lne_temperature")
        self.gridLayout.addWidget(self.ui_lne_temperature, 1, 1, 1, 2)
        self.ui_lne_temperature_max = QtWidgets.QLineEdit(self.groupBox)
        self.ui_lne_temperature_max.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_lne_temperature_max.setObjectName("ui_lne_temperature_max")
        self.gridLayout.addWidget(self.ui_lne_temperature_max, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.ui_lne_temperature_min = QtWidgets.QLineEdit(self.groupBox)
        self.ui_lne_temperature_min.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_lne_temperature_min.setObjectName("ui_lne_temperature_min")
        self.gridLayout.addWidget(self.ui_lne_temperature_min, 0, 1, 1, 1)
        self.ui_lab_alarm = QtWidgets.QLabel(self.groupBox)
        self.ui_lab_alarm.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ui_lab_alarm.setText("")
        self.ui_lab_alarm.setObjectName("ui_lab_alarm")
        self.gridLayout.addWidget(self.ui_lab_alarm, 2, 0, 1, 3)
        self.ui_btn_OK = QtWidgets.QPushButton(self.centralwidget)
        self.ui_btn_OK.setGeometry(QtCore.QRect(650, 520, 75, 23))
        self.ui_btn_OK.setObjectName("ui_btn_OK")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 321, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ui_btn_connect = QtWidgets.QPushButton(self.groupBox_2)
        self.ui_btn_connect.setObjectName("ui_btn_connect")
        self.gridLayout_2.addWidget(self.ui_btn_connect, 0, 2, 1, 1)
        self.ui_cb_com = QtWidgets.QComboBox(self.groupBox_2)
        self.ui_cb_com.setObjectName("ui_cb_com")
        self.gridLayout_2.addWidget(self.ui_cb_com, 0, 0, 1, 1)
        self.ui_btn_refresh = QtWidgets.QPushButton(self.groupBox_2)
        self.ui_btn_refresh.setObjectName("ui_btn_refresh")
        self.gridLayout_2.addWidget(self.ui_btn_refresh, 0, 1, 1, 1)
        self.ui_lab_status = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_lab_status.sizePolicy().hasHeightForWidth())
        self.ui_lab_status.setSizePolicy(sizePolicy)
        self.ui_lab_status.setMinimumSize(QtCore.QSize(50, 50))
        self.ui_lab_status.setStyleSheet("border-image: url(:/img/io_red.png);")
        self.ui_lab_status.setText("")
        self.ui_lab_status.setObjectName("ui_lab_status")
        self.gridLayout_2.addWidget(self.ui_lab_status, 0, 3, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 140, 331, 371))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ui_lw_visitor_info = QtWidgets.QListWidget(self.groupBox_3)
        self.ui_lw_visitor_info.setObjectName("ui_lw_visitor_info")
        self.gridLayout_3.addWidget(self.ui_lw_visitor_info, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ui_lne_temperature, self.ui_btn_OK)
        MainWindow.setTabOrder(self.ui_btn_OK, self.ui_cb_com)
        MainWindow.setTabOrder(self.ui_cb_com, self.ui_btn_refresh)
        MainWindow.setTabOrder(self.ui_btn_refresh, self.ui_btn_connect)
        MainWindow.setTabOrder(self.ui_btn_connect, self.ui_lw_visitor_info)
        MainWindow.setTabOrder(self.ui_lw_visitor_info, self.ui_lne_temperature_min)
        MainWindow.setTabOrder(self.ui_lne_temperature_min, self.ui_lne_temperature_max)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "体温录入"))
        self.groupBox.setTitle(_translate("MainWindow", "健康状况"))
        self.ui_lne_temperature.setText(_translate("MainWindow", "35.0"))
        self.ui_lne_temperature_max.setText(_translate("MainWindow", "37.3"))
        self.label.setText(_translate("MainWindow", "当前体温"))
        self.label_2.setText(_translate("MainWindow", "正常体温范围"))
        self.ui_lne_temperature_min.setText(_translate("MainWindow", "36.0"))
        self.ui_btn_OK.setText(_translate("MainWindow", "提交"))
        self.ui_btn_OK.setShortcut(_translate("MainWindow", "Return"))
        self.groupBox_2.setTitle(_translate("MainWindow", "连接扫描枪"))
        self.ui_btn_connect.setText(_translate("MainWindow", "打开"))
        self.ui_btn_refresh.setText(_translate("MainWindow", "刷新"))
        self.groupBox_3.setTitle(_translate("MainWindow", "人员信息"))
import res
